controllers:
  sessions:
    layout: "login_layout"
models:
  user:
    name:
      max_length: 50
    email:
      max_length: 255
      regex_valid: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
    password:
      min_length: 8
      max_length: 32
page: 10
avatar:
  lg: 120
  md: 80
  sm: 50
  xs: 30
