max_book: 10
add_book_not_status: 5
default_email: "bibliosphere_library@gmail.com"
email: "library@gmail.com"
phone: "+(84) 911-577-985"
default_status: 0
cart_item_default_status: 0
card_time_setting: "%H:%M:%S %d/%m/%Y"
card_item_min_delete: 1
file_storage: "app/assets/images"
file_permissions: "wb"
views:
  home:
    banner_count: 100
    banner_star: 5
controllers:
  episodes:
    all:
      per_page: 12
  sessions:
    layout: "login_layout"
models:
  category:
    top_count: 5
  episode:
    trend_count: 4
    most_count: 6
    limit: 6
  user:
    name:
      max_length: 50
    email:
      max_length: 255
      regex_valid: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
    password:
      min_length: 8
      max_length: 32
  publisher:
    name:
      max_length: 50
  author:
    name:
      max_length: 50
    intro:
      max_length: 550
    limit: 6
  book_borrow:
    max_borrow_duration: 5
date_format: "%Y-%m-%d"
page: 10
avatar:
  lg: 120
  md: 80
  sm: 50
  xs: 30
